// Emits a template's `components/Icon.tsx` from the @fluxnative/icons
// table: the same closed names, drawn with react-native-svg (on both
// hosts' allow-lists), coloured from the template palette.

import { ICONS, type IconSpec } from '@fluxnative/icons/table';

export function emitIcon(table: Record<string, IconSpec> = ICONS): string {
  const rows = Object.entries(table)
    .map(([name, spec]) => {
      const fill = spec.fillPath !== undefined ? `, fillPath: ${JSON.stringify(spec.fillPath)}` : '';
      return `  ${JSON.stringify(name)}: { path: ${JSON.stringify(spec.path)}${fill} },`;
    })
    .join('\n');
  return `// Generated by @fluxnative/catalog from @fluxnative/icons — do not edit by hand.
// One closed set of icon names; \`tsc\` rejects a typo. Draws a 2px round
// stroke on a 24-unit grid; \`filled\` paints the glyph (selected tab, saved heart).
// A decorative icon is a bare <Svg>; a labelled one is wrapped in a View that
// carries the accessibility props, because react-native-svg's web build forwards
// every unknown prop to the DOM <svg> and React warns on \`accessible\`.

import React from 'react';
import { View, type StyleProp, type ViewStyle } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { usePalette } from '../theme/usePalette';

export const ICONS = {
${rows}
} as const;

export type IconName = keyof typeof ICONS;

export interface IconProps {
  name: IconName;
  /** Width and height in px. Default 24. */
  size?: number;
  /** Any colour value. Defaults to the palette's \`foreground\`. */
  color?: string;
  /** Stroke width on the 24-unit grid. Default 2. */
  strokeWidth?: number;
  /** Paint the glyph instead of outlining it. */
  filled?: boolean;
  style?: StyleProp<ViewStyle>;
  /** Screen-reader name. Omit for a decorative icon next to a label. */
  accessibilityLabel?: string;
}

export default function Icon({ name, size = 24, color, strokeWidth = 2, filled = false, style, accessibilityLabel }: IconProps) {
  const palette = usePalette();
  const spec: { path: string; fillPath?: string } = ICONS[name];
  const paint = color ?? palette.foreground;
  const d = filled ? (spec.fillPath ?? spec.path) : spec.path;
  const svg = (
    <Svg width={size} height={size} viewBox="0 0 24 24" style={accessibilityLabel === undefined ? style : undefined}>
      <Path d={d} fill={filled ? paint : 'none'} stroke={paint} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
  if (accessibilityLabel === undefined) return svg;
  return (
    <View style={style} accessible accessibilityRole="image" accessibilityLabel={accessibilityLabel}>
      {svg}
    </View>
  );
}
`;
}
