// Emits `generated/tokens.ts`: plain constants a StyleSheet, the runtime
// class resolver and the chrome components read. It imports nothing, so a
// Flux template can copy it as-is.

import type { TokenModel } from './model.ts';

const HEADER = `// Generated by @flux-ui/tokens from tokens/*.tokens.json — do not edit.
// Run \`pnpm tokens\` after changing a token file.
`;

const literal = (value: unknown) => JSON.stringify(value, null, 2);

export function emitTs(model: TokenModel): string {
  const schemes = Object.keys(model.colors);
  const first = schemes[0];
  if (!first) throw new Error('No color scheme to emit');
  const colorDocs = Object.keys(model.colors[first] ?? {})
    .map((name) => {
      const doc = model.colorDescriptions[name];
      return doc ? `  /** ${doc} */\n  | '${name}'` : `  | '${name}'`;
    })
    .join('\n');
  // React Native takes font weights as strings.
  const fontWeight = Object.fromEntries(Object.entries(model.fontWeight).map(([k, v]) => [k, String(v)]));

  return `${HEADER}
export const colors = ${literal(model.colors)} as const;

/** Semantic color names. Use these, never raw hex, so dark mode keeps working. */
export type ColorName =
${colorDocs};

export type ColorScheme = ${schemes.map((s) => `'${s}'`).join(' | ')};

/** Tailwind spacing: \`p-4\` = 4 × spacingUnit. */
export const spacingUnit = ${model.spacingUnit};

export const radius = ${literal(model.radius)} as const;
export type RadiusName = keyof typeof radius;

export const text = ${literal(model.text)} as const;
export type TextSize = keyof typeof text;

export const fontWeight = ${literal(fontWeight)} as const;
export type FontWeightName = keyof typeof fontWeight;

/** Milliseconds. */
export const duration = ${literal(model.duration)} as const;

/** Cubic-bezier control points (x1, y1, x2, y2). */
export const easing = ${literal(model.easing)} as const;

/** Glass ladder parameters for the blur and translucent tiers. */
export const glass = ${literal(model.glass)} as const;

/** Navigation chrome metrics for the custom (non-native) tiers. */
export const chrome = ${literal(model.chrome)} as const;
`;
}
