// Emits the Uniwind (Tailwind v4, CSS-first) theme. Two outputs share it:
// `generated/theme.css` (the theme alone) and, with `--global-css <path>`,
// an app's whole global.css. Apps should use the second: Uniwind registers
// light/dark themes by scanning the `@variant` blocks in its CSS entry file,
// so the theme lives in that file rather than behind an @import.
//
// Spacing, radius and type keep Tailwind's defaults (the tokens mirror
// them). Colors are the exception: the default palette is reset so only
// semantic names exist, and `bg-blue-500` produces nothing.

import type { TokenModel } from './model.ts';

const HEADER = '/* Generated by @flux-ui/tokens from tokens/*.tokens.json — do not edit. */';

export function emitTheme(model: TokenModel): string {
  const schemes = Object.entries(model.colors);
  const [, first] = schemes[0] ?? [];
  if (!first) throw new Error('No color scheme to emit');
  const names = Object.keys(first);

  // `unset` registers each name as a utility (bg-*, text-*, border-*) whose
  // value comes from the active @variant below — the same declaration
  // Uniwind generates for theme variables. `--color-*: initial` must come
  // first, or it would erase these too.
  const register = names.map((name) => `  --color-${name}: unset;`).join('\n');
  const variants = schemes
    .map(([scheme, map]) => {
      const vars = names.map((name) => `      --color-${name}: ${map[name]};`).join('\n');
      return `    @variant ${scheme} {\n${vars}\n    }`;
    })
    .join('\n');

  return `@theme {
  /* Semantic colors only: drop Tailwind's palette. */
  --color-*: initial;
  --color-white: #ffffff;
  --color-black: #000000;
${register}
}

@layer theme {
  :root {
${variants}
  }
}
`;
}

export function emitCss(model: TokenModel): string {
  return `${HEADER}\n/* Import after 'tailwindcss' and 'uniwind', or generate the whole global.css with --global-css. */\n\n${emitTheme(model)}`;
}

/** A complete global.css for a Uniwind app. */
export function emitGlobalCss(model: TokenModel): string {
  return `${HEADER}
/* Regenerate with \`pnpm tokens\` (or \`flux-ui tokens\`) — it is the Uniwind CSS entry file. */

@import 'tailwindcss';
@import 'uniwind';

${emitTheme(model)}`;
}
