// Generated by @fluxnative/catalog from @fluxnative/tokens — do not edit by hand.
// Colour overrides: none. Regenerate with `fluxnative-catalog emit`.

export type ColorScheme = 'light' | 'dark';

/** Semantic colour names. Screens use these, never a raw hex, so a palette swap is one file. */
export type ColorName =
  /** App canvas behind every screen. */
  | 'background'
  /** Primary text and icons on background. */
  | 'foreground'
  /** Raised content surface (cards, cells). */
  | 'card'
  /** Text on card. */
  | 'card-foreground'
  /** Menus and popovers. */
  | 'popover'
  /** Text on popover. */
  | 'popover-foreground'
  /** Brand / main action. */
  | 'primary'
  /** Text and icons on primary. */
  | 'primary-foreground'
  /** Secondary action fill. */
  | 'secondary'
  /** Text on secondary. */
  | 'secondary-foreground'
  /** Quiet fill: inputs, skeletons, grouped backgrounds. */
  | 'muted'
  /** Secondary text. */
  | 'muted-foreground'
  /** Pressed / selected fill. */
  | 'accent'
  /** Text on accent. */
  | 'accent-foreground'
  /** Destructive action and errors. */
  | 'destructive'
  /** Text and icons on a destructive fill (badges, danger buttons). */
  | 'destructive-foreground'
  /** Positive status. */
  | 'success'
  /** Caution status. */
  | 'warning'
  /** Hairlines and outlines. */
  | 'border'
  /** Text field outline. */
  | 'input'
  /** Focus ring. */
  | 'ring'
  /** Dimming layer under sheets and over media. */
  | 'scrim'
  /** Translucent glass tier fill (no blur available). */
  | 'glass-fill'
  /** Fill laid over a backdrop blur on the blur tier (web). */
  | 'glass-blur-fill'
  /** Glass rim. */
  | 'glass-border'
  /** Specular highlight on translucent glass. */
  | 'glass-highlight'
  /** Opaque glass tier (Reduce Transparency / Increase Contrast). */
  | 'glass-opaque';

export type Palette = { readonly [K in ColorName]: string };

export const colors: { readonly [S in ColorScheme]: Palette } = {
  "light": {
    "background": "#ffffff",
    "foreground": "#0a0a0b",
    "card": "#ffffff",
    "card-foreground": "#0a0a0b",
    "popover": "#ffffff",
    "popover-foreground": "#0a0a0b",
    "primary": "#007aff",
    "primary-foreground": "#ffffff",
    "secondary": "#f2f2f7",
    "secondary-foreground": "#0a0a0b",
    "muted": "#f2f2f7",
    "muted-foreground": "#6e6e73",
    "accent": "#e9e9ee",
    "accent-foreground": "#0a0a0b",
    "destructive": "#ff3b30",
    "destructive-foreground": "#ffffff",
    "success": "#34c759",
    "warning": "#ff9500",
    "border": "rgba(60, 60, 67, 0.18)",
    "input": "rgba(60, 60, 67, 0.18)",
    "ring": "#007aff",
    "scrim": "rgba(0, 0, 0, 0.4)",
    "glass-fill": "rgba(255, 255, 255, 0.72)",
    "glass-blur-fill": "rgba(255, 255, 255, 0.5)",
    "glass-border": "rgba(255, 255, 255, 0.6)",
    "glass-highlight": "rgba(255, 255, 255, 0.55)",
    "glass-opaque": "#f9f9f9"
  },
  "dark": {
    "background": "#000000",
    "foreground": "#f5f5f7",
    "card": "#1c1c1e",
    "card-foreground": "#f5f5f7",
    "popover": "#2c2c2e",
    "popover-foreground": "#f5f5f7",
    "primary": "#0a84ff",
    "primary-foreground": "#ffffff",
    "secondary": "#2c2c2e",
    "secondary-foreground": "#f5f5f7",
    "muted": "#1c1c1e",
    "muted-foreground": "#98989f",
    "accent": "#2c2c2e",
    "accent-foreground": "#f5f5f7",
    "destructive": "#ff453a",
    "destructive-foreground": "#ffffff",
    "success": "#30d158",
    "warning": "#ff9f0a",
    "border": "rgba(84, 84, 88, 0.6)",
    "input": "rgba(84, 84, 88, 0.6)",
    "ring": "#0a84ff",
    "scrim": "rgba(0, 0, 0, 0.55)",
    "glass-fill": "rgba(30, 30, 32, 0.72)",
    "glass-blur-fill": "rgba(30, 30, 32, 0.45)",
    "glass-border": "rgba(255, 255, 255, 0.14)",
    "glass-highlight": "rgba(255, 255, 255, 0.16)",
    "glass-opaque": "#1c1c1e"
  }
};

/** The scheme this template is designed for; `null` follows the system setting. */
export const lockedScheme: ColorScheme | null = null;

/** One spacing step in px (`space[4]` is four units). */
export const spacingUnit = 4;

/** Tailwind's spacing scale in px: `space[4]` = 16, `space[0.5]` = 2. */
export const space = {
  "0": 0,
  "1": 4,
  "2": 8,
  "3": 12,
  "4": 16,
  "5": 20,
  "6": 24,
  "7": 28,
  "8": 32,
  "9": 36,
  "10": 40,
  "11": 44,
  "12": 48,
  "14": 56,
  "16": 64,
  "20": 80,
  "24": 96,
  "28": 112,
  "32": 128,
  "36": 144,
  "40": 160,
  "0.5": 2,
  "1.5": 6,
  "2.5": 10,
  "3.5": 14
} as const;
export type SpaceStep = keyof typeof space;

export const radius = {
  "xs": 2,
  "sm": 4,
  "DEFAULT": 4,
  "md": 6,
  "lg": 8,
  "xl": 12,
  "2xl": 16,
  "3xl": 24,
  "4xl": 32,
  "full": 9999
} as const;
export type RadiusName = keyof typeof radius;

/** Font size and line height in px; the system font carries the voice. */
export const text = {
  "xs": {
    "fontSize": 12,
    "lineHeight": 16
  },
  "sm": {
    "fontSize": 14,
    "lineHeight": 20
  },
  "base": {
    "fontSize": 16,
    "lineHeight": 24
  },
  "lg": {
    "fontSize": 18,
    "lineHeight": 28
  },
  "xl": {
    "fontSize": 20,
    "lineHeight": 28
  },
  "2xl": {
    "fontSize": 24,
    "lineHeight": 32
  },
  "3xl": {
    "fontSize": 30,
    "lineHeight": 36
  },
  "4xl": {
    "fontSize": 36,
    "lineHeight": 40
  },
  "5xl": {
    "fontSize": 48,
    "lineHeight": 48
  },
  "6xl": {
    "fontSize": 60,
    "lineHeight": 60
  }
} as const;
export type TextSize = keyof typeof text;

/** React Native takes font weights as strings. */
export const fontWeight = {
  "thin": "100",
  "extralight": "200",
  "light": "300",
  "normal": "400",
  "medium": "500",
  "semibold": "600",
  "bold": "700",
  "extrabold": "800",
  "black": "900"
} as const;
export type FontWeightName = keyof typeof fontWeight;

/** Milliseconds. */
export const duration = {
  "fast": 150,
  "normal": 250,
  "slow": 400
} as const;

/** Cubic-bezier control points (x1, y1, x2, y2) for `Easing.bezier`. */
export const easing = {
  "standard": [
    0.2,
    0,
    0,
    1
  ],
  "emphasized": [
    0.3,
    0,
    0,
    1
  ]
} as const;

/** Glass ladder parameters, for templates that declare the `glass` capability. */
export const glass = {
  "blurRadius": 24,
  "saturate": 1.8
} as const;

/** Navigation chrome metrics. */
export const chrome = {
  "appBarHeight": 44,
  "tabBarHeight": 56,
  "tabBarInset": 16
} as const;
