// A small "AI" tag for content a model made: a result card, a generated
// image, a summary. Screen readers hear "Generated by AI". Put it next to
// the content it labels; pair facts with their source.

import React from 'react';
import { StyleSheet, Text, View, type StyleProp, type ViewStyle } from 'react-native';
import { shape, space, type } from '../theme/tokens';
import { usePalette, type Palette } from '../theme/usePalette';
import Icon from './Icon';

export type AiBadgeVariant = 'filled' | 'tonal';

export interface AiBadgeProps {
  /** Visible text. Default 'AI'. */
  label?: string;
  /** 'filled' (default) on `tertiary`, readable over photos; 'tonal' on `muted`, quieter inside a card. */
  variant?: AiBadgeVariant;
  /** Default 'Generated by AI'. */
  accessibilityLabel?: string;
  style?: StyleProp<ViewStyle>;
}

function colorsOf(variant: AiBadgeVariant, palette: Palette): { fill: string; ink: string } {
  return variant === 'filled'
    ? { fill: palette.tertiary, ink: palette['tertiary-foreground'] }
    : { fill: palette.muted, ink: palette['foreground-soft'] };
}

export default function AiBadge({ label = 'AI', variant = 'filled', accessibilityLabel = 'Generated by AI', style }: AiBadgeProps) {
  const palette = usePalette();
  const { fill, ink } = colorsOf(variant, palette);
  return (
    <View
      accessible
      accessibilityRole="text"
      accessibilityLabel={accessibilityLabel}
      style={[styles.badge, { backgroundColor: fill, borderRadius: shape.chip }, style]}
    >
      <Icon name="sparkle" size={12} color={ink} />
      <Text numberOfLines={1} style={[type.caps, styles.label, { color: ink }]}>
        {label}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: space[2],
    paddingVertical: space[0.5],
  },
  label: { marginLeft: space[1] },
});
